AWSTemplateFormatVersion: "2010-09-09"
Description: Lab 6.1.1 - ASG from Instance

Resources:
  RingerDebian:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref RingerLaunchTemplate
        Version: 1

  RingerLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
        ImageId: ami-07d02ee1eeb0c996c  # Debian buster image
        InstanceType: t2.medium

  RingerASG:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: 
        - us-east-1c
      MaxSize: '1'
      MinSize: '1'
      DesiredCapacity: '1'
      LaunchConfigurationName: !Ref RingerLaunchConfig
    UpdatePolicy:
      AutoScalingReplacingUpdate:
        WillReplace: 'true'