AWSTemplateFormatVersion: 2010-09-09
Description: 5.2.1

Resources:
  RingerUbuntu2Template:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: RingerUbuntu2Template
      LaunchTemplateData:
        ImageId: ami-0b0ea68c435eb488d #ami-04b3c39a8a1c62b76
        InstanceType: t2.micro

  EC2:
    Type: AWS::EC2::Instance
    Properties: 
      LaunchTemplate:
        LaunchTemplateId: !Ref RingerUbuntu2Template
        Version: 1
      KeyName: ringer-stelligent
      Tags: 
      - Key: "Name"
        Value: "ringer-instance"
      - Key: "user"
        Value: "gringer_aa"
      NetworkInterfaces:
      - AssociatePublicIpAddress: True
        DeleteOnTermination: True
        SubnetId:
          !ImportValue SubnetId
        DeviceIndex: '0'
        GroupSet:
          - Ref: SecurityGroup

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ICMP (for ping) and ssh traffic into your instance.
      VpcId:
        !ImportValue VPCID
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: icmp 
        FromPort: 8
        ToPort: -1
        CidrIp: 0.0.0.0/0

  ElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref EC2

Outputs:
  InstanceID:
    Description: Instance ID
    Value: !Ref EC2
    Export:
      Name: Ringer-EC2-ID
  InstancePrivateIP:
    Description: EC2 Instance Privte IP address
    Value: !GetAtt EC2.PrivateIp
    Export:
      Name: Ringer-EC2-Private-IP
  InstancePublicIP:
    Description: EC2 Instance Public IP address
    Value: !GetAtt EC2.PublicIp
    Export:
      Name: Ringer-EC2-Public-IP