AWSTemplateFormatVersion: "2010-09-09"
Description: Lab 1.2.3
Parameters:
    BucketParameter:
        Description: BucketParameter
        Type: String
    UserParameter:
        Description: UserParameter
        Type: String

Conditions:
  PreferredRegion: !Equals 
    - !Ref AWS::Region
    - us-east-1

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        'Fn::If':
          - PreferredRegion
          - !Join
            - ''
            - - !Ref AWS::AccountId
              - 'second'
              - !Ref BucketParameter
          - !Join
              - ''
              - - !Ref AWS::Region
                - !Ref BucketParameter
  User:      
    Type: AWS::IAM::User
    Properties:
      Path: "/"
      ManagedPolicyArns: 
        - !ImportValue MyManagedPolicy
      UserName: ringer-exportUser
      LoginProfile:
        Password: myP@ssW0rd