AWSTemplateFormatVersion: "2010-09-09"
Description: Lab 1.3

Parameters:
    BucketParameter:
        Default: gr-m01x3-training
        Description: BucketParameter
        Type: String
    FriendlyName:
        Type: String
        Default: gr-m01u3-train-use1

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::Region}-${FriendlyName}