AWSTemplateFormatVersion: "2010-09-09"
Description: My most minimal template possible

Parameters:
    BucketParameter:
        Description: BucketParameter
        Type: String
    UserParameter:
        Description: UserParameter
        Type: String

Conditions:
  PreferredRegion: !Equals 
    - !Ref AWS::Region
    - us-east-1

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        'Fn::If':
          - PreferredRegion
          - !Join
            - ''
            - - !Ref AWS::AccountId
              - !Ref BucketParameter
          - !Join
              - ''
              - - !Ref AWS::Region
                - !Ref BucketParameter
  User:      
    Type: AWS::IAM::User
    Properties:
      Path: "/"
      UserName: !Ref UserParameter
      LoginProfile:
        Password: myP@ssW0rd

  S3ReadOnlyPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties: 
      Description: A read-only policy for ringer-s3user
      ManagedPolicyName: ringer-s3policy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: Allow
          Action:
          - s3:Get*
          - s3:List*
          - s3-object-lambda:Get*
          - s3-object-lambda:List*
          Resource: 
            - 'arn:aws:s3:::ringer-test'
      Users: 
        - ringer-s3user

Outputs:
  MyManagedPolicy:
    Description: MyManagedPolicy
    Value:
      Ref: S3ReadOnlyPolicy
    Export:
      Name: MyManagedPolicy 
    Value:
        Ref: S3ReadOnlyPolicy