AWSTemplateFormatVersion: "2010-09-09"
Description: My most minimal template possible

Parameters:
    BucketParameter:
        Description: BucketParameter
        Type: String

Conditions:
  PreferredRegion: !Equals 
    - !Ref AWS::Region
    - us-east-1

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        'Fn::If':
          - PreferredRegion
          - !Join
            - ''
            - - !Ref AWS::AccountId
              - !Ref BucketParameter
          - !Join
              - ''
              - - !Ref AWS::Region
                - !Ref BucketParameter