AWSTemplateFormatVersion: 2010-09-09
Parameters:
  NameParam:
    Type: String
    Default: "Ringer"
    AllowedPattern: ^[A-Za-z.-]+$
    ConstraintDescription: Only letters, periods, and hyphens allowed
    MaxLength: 50
  TeamParam:
    Type: String
    Default: "SRE"
    AllowedPattern: ^[0-9A-Za-z_.-]+$
    ConstraintDescription: Only numbers, letters, underscores, periods, and hyphens allowed
    MaxLength: 50
  TimeZoneParam:
    Type: String
    Default: CST
    MaxLength: 3
  StateParam:
    Type: String
    Default: TN
    MaxLength: 2
  StartDateParam:
    Type: String
    Default: "01/01/2022"
    AllowedPattern: ^(?:(?:(?:0?[13578]|1[02])(\/|-|\.)31)\1|(?:(?:0?[1,3-9]|1[0-2])(\/|-|\.)(?:29|30)\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:0?2(\/|-|\.)29\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:(?:0?[1-9])|(?:1[0-2]))(\/|-|\.)(?:0?[1-9]|1\d|2[0-8])\4(?:(?:1[6-9]|[2-9]\d)?\d{2})$
    ConstraintDescription: Please enter a valid date mm/dd/yyyy, mm.dd.yyyy, or mm-dd-yyy
    MaxLength: 10

Resources:
  Name:
    Type: AWS::SSM::Parameter
    Properties: 
      DataType: text
      Description: Name
      Name: RingerName
      Type: String
      Value: !Ref NameParam
  Team:
    Type: AWS::SSM::Parameter
    Properties: 
      DataType: text
      Description: Team
      Name: RingerTeam
      Type: String
      Value: !Ref TeamParam
  TimeZone:
    Type: AWS::SSM::Parameter
    Properties: 
      DataType: text
      Description: TimeZone
      Name: RingerTimeZone
      Type: String
      Value: !Ref TimeZoneParam
  State:
    Type: AWS::SSM::Parameter
    Properties: 
      DataType: text
      Description: State
      Name: RingerState
      Type: String
      Value: !Ref StateParam
  StartDate:
    Type: AWS::SSM::Parameter
    Properties: 
      DataType: text
      Description: StartDate
      Name: RingerStartDate
      Type: String
      Value: !Ref StartDateParam